<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.qiongguichou</groupId>
        <artifactId>qgc-server</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>qgc-wechat</artifactId>
    <description>微信相关模块(OAuth授权/分享/二维码)</description>

    <dependencies>
        <!-- qgc-core -->
        <dependency>
            <groupId>com.qiongguichou</groupId>
            <artifactId>qgc-core</artifactId>
        </dependency>

        <!-- qgc-user -->
        <dependency>
            <groupId>com.qiongguichou</groupId>
            <artifactId>qgc-user</artifactId>
        </dependency>

        <!-- weixin-java-mp 微信公众号SDK -->
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-mp</artifactId>
        </dependency>

        <!-- Spring Boot Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
</project>