<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.qiongguichou</groupId>
        <artifactId>qiongguichou</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>qgc-server</artifactId>
    <packaging>pom</packaging>
    <description>后端服务模块聚合</description>

    <modules>
        <module>qgc-common</module>
        <module>qgc-core</module>
        <module>qgc-user</module>
        <module>qgc-campaign</module>
        <module>qgc-payment</module>
        <module>qgc-wallet</module>
        <module>qgc-content</module>
        <module>qgc-wechat</module>
        <module>qgc-admin</module>
        <module>qgc-job</module>
        <module>qgc-server-main</module>
    </modules>

    <dependencies>
        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>