<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.qiongguichou</groupId>
        <artifactId>qiongguichou</artifactId>
        <version>1.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>qgc-admin</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.qiongguichou</groupId>
            <artifactId>qgc-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.qiongguichou</groupId>
            <artifactId>qgc-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.qiongguichou</groupId>
            <artifactId>qgc-campaign</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.qiongguichou</groupId>
            <artifactId>qgc-payment</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.qiongguichou</groupId>
            <artifactId>qgc-wallet</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.qiongguichou</groupId>
            <artifactId>qgc-content</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mindrot</groupId>
            <artifactId>jbcrypt</artifactId>
            <version>0.4</version>
        </dependency>
    </dependencies>
</project>